---
# tasks file for kvm
- name: include kvm debian
  import_tasks: debian.yml
  tags:
    - kvm

- name: include kvm vm predeploy
  import_tasks: vm_predeploy.yml
  tags:
    - vm_predeploy

- name: vm01 deploy
  import_tasks: vm01_deploy.yml
  tags:
    - vm01_deploy

- name: vm02 deploy
  import_tasks: vm02_deploy.yml
  tags:
    - vm02_deploy
