---
# defaults file for kvm  

    libvirt_folder: "/var/lib/libvirt/"
    image_pool_dir: "/var/lib/libvirt/"
    image_pool_name: "images"
    image_base_dir: "/var/lib/libvirt/images/"
    image_base_name: "bionic-server-cloudimg-amd64.img"
    image_custom_name: ubnt1804
    vm_folders: ["{{ image_base_dir }}vm01/","{{ image_base_dir }}vm02/"]
    vm_images: ["{{ image_base_dir }}vm01/snapshot-{{ image_custom_name }}.qcow2","{{ image_base_dir }}vm02/snapshot-{{ image_custom_name }}.qcow2"]
    image_base_url: ["https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img"]
    libvirt_uri: "qemu:///system"
    root_pass: "1"
    host01: "vm01"
    host02: "vm02"
    images: "images"