#delay can be replaced with a smaller value for your situation
- name: vm01 is starting... wait a sec... go get some coffee   
  wait_for:
    delay: 
  #change this value for your case
    timeout: 10
    
- name: Validating if the vm01 is UP and OPENED the PORT
  wait_for:
      host: vm01
      port: 22
      delay: 5
      timeout: 10
      state: started
      msg: "WebServer PORT is not Listening"
  ignore_errors: true

- name: install on vm01 some packeges for docker (pip)
  become: true
  apt:
      state: latest
      name: "{{ item }}"
      update_cache: yes
  with_items:
    - python3-pip

- name: install some docker package 
  become: true 
  pip:
      name: "{{ item }}"
  with_items:
    - docker
    - docker-compose

- name: checking for wordpress folder 
  stat: path="{{ item }}"
  register: wp_folder_stat
  with_items: 
  - "{{ wordpress_base_dir }}"

- name: create wordpress folders for vm01 if not exist
  become: true
  file:  
    path: "{{ item.item }}"
    state: directory 
  when: item.stat.exists == false 
  with_items: 
  - "{{ wp_folder_stat.results }}" 

- name: template a docker_compose file to vm01 folders
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: 
    - { src: 'docker-compose.yaml.j2', dest: "/usr/wordpress/docker-compose.yaml" }

- name: Create and start services wp/db
  become: true
  docker_compose:
    project_src: /usr/wordpress/
  register: output

- debug:
    var: output