#delay can be replaced with a smaller value for your situation
- name: vm02 is starting... wait a sec... go get some coffee   
  wait_for:
    delay: 500
  #change this value for your case
    timeout: 1000
    
- name: Validating if the vm02 is UP and OPENED the PORT
  wait_for:
      host: vm02
      port: 22
      delay: 30
      timeout: 60
      state: started
      msg: "WebServer PORT is not Listening"
  ignore_errors: true

- name: install on vm02 some packeges for docker (pip)
  become: true
  apt:
      state: latest
      name: "{{ item }}"
      update_cache: yes
  with_items:
    - python3-pip

- name: install some docker package 
  become: true 
  pip:
      name: "{{ item }}"
  with_items:
    - docker
    - docker-compose

- name: checking for wordpress folder 
  stat: path="{{ item }}"
  register: wp_folder_stat
  with_items: 
  - "{{ wordpress_base_dir }}"

- name: create wordpress folders for vm02 if not exist
  become: true
  file:  
    path: "{{ item.item }}"
    state: directory 
  when: item.stat.exists == false 
  with_items: 
  - "{{ wp_folder_stat.results }}" 

- name: template a docker_compose file to vm02 folders
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: 
    - { src: 'docker-compose.yaml.j2', dest: "/usr/wordpress/docker-compose.yaml" }

- name:  get containers info (vm02)
  become: true
  shell:
    cmd: docker ps | grep wordpress_db_1 | awk '{ print $12 }'
  register: cn_exists

- name: Create and start services wp/db
  become: true
  docker_compose:
    project_src: /usr/wordpress/
  register: output
  when: cn_exists.stdout != containers_check

- debug:
    var: output